/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6b9e4218-9ce9-4baa-9089-8f8d19a2fc36",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5dWyw4SJ0",
    "aws_user_pools_web_client_id": "6hoh6kblh1dt0pv2phmotls7d7",
    "oauth": {}
};


export default awsmobile;
